# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    elastic_stack:
      repo: elastic/elastic_stack
      ref: 7.0.0
    elasticsearch:
      repo: elastic/elasticsearch
      ref: 6.4.0
    graylog:
      repo: graylog/graylog
      ref: 0.9.0
    java:
      repo: puppetlabs/java
      ref: 6.3.0
    mongodb:
      repo: puppet/mongodb
      ref: 3.1.0
    selinux:
      repo: "puppet/selinux"
      ref: 3.2.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 6.3.0
    systemd:
      repo: camptocamp/systemd
      ref: 2.9.0
  repositories:
    nginx:
      repo: "https://github.com/aursu/puppet-nginx.git"
      ref: "tags/v1.1.1-rc0.5"
    rlimits:
      repo: "https://github.com/aursu/puppet-rlimits.git"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    host_core:
      repo: https://github.com/puppetlabs/puppetlabs-host_core.git
      puppet_version: ">= 6.0.0"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"