# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    augeas_core:
      repo: puppetlabs/augeas_core
      puppet_version: ">= 6.0.0"
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    datacat:
      repo: richardc/datacat
      ref: 0.6.2
    elastic_stack:
      repo: puppet/elastic_stack
      ref: 9.0.0
    elasticsearch:
      repo: puppet/elasticsearch
      ref: 8.1.0
    graylog:
      repo: graylog/graylog
      ref: 2.0.0
    host_core:
      repo: puppetlabs/host_core
      puppet_version: ">= 6.0.0"
    java:
      repo: puppetlabs/java
      ref: 10.1.2
    mongodb:
      repo: puppet/mongodb
      ref: 6.0.1
    selinux_core:
      repo: puppetlabs/selinux_core
      puppet_version: ">= 6.0.0"
    selinux:
      repo: puppet/selinux
      ref: 4.0.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    systemd:
      repo: puppet/systemd
      ref: 6.0.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
  repositories:
    nginx:
      repo: https://github.com/aursu/puppet-nginx.git
      ref: tags/v4.4.1-rc0.2
    rlimits:
      repo: https://github.com/aursu/puppet-rlimits.git
      ref: tags/v1.0.0

